
/*********************ADMIN_PERMISSION*************************/
DROP TABLE IF EXISTS `ADMIN_PERMISSION`;
CREATE TABLE `ADMIN_PERMISSION` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `LAST_MODIFY_TIME` DATETIME DEFAULT NULL,
  `OPERATOR` BIGINT(20) DEFAULT NULL,
  `EXPRESSION` VARCHAR(255) COLLATE UTF8_BIN DEFAULT NULL,
  `NAME` VARCHAR(255) COLLATE UTF8_BIN DEFAULT NULL,
  `RESOURCE_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;
INSERT ADMIN_PERMISSION(`NAME`,`EXPRESSION`,`RESOURCE_ID`,`CREATE_TIME`,`LAST_MODIFY_TIME`,`OPERATOR`)
  VALUE ("首页菜单权限","menu:/home",1,NOW(),NOW(),1);

/*********************ADMIN_RESOURCE*************************/
DROP TABLE IF EXISTS `ADMIN_RESOURCE`;
CREATE TABLE `ADMIN_RESOURCE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `LAST_MODIFY_TIME` DATETIME DEFAULT NULL,
  `OPERATOR` BIGINT(20) DEFAULT NULL,
  `LEVEL` SMALLINT(2) DEFAULT NULL,
  `PATH` VARCHAR(256) COLLATE UTF8_BIN DEFAULT NULL,
  `NAME` VARCHAR(20) COLLATE UTF8_BIN DEFAULT NULL,
  `TYPE` SMALLINT(2) DEFAULT NULL,
  `PARENT_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

INSERT ADMIN_RESOURCE(`NAME`,`TYPE`,`LEVEL`,`PATH`,`PARENT_ID`,`CREATE_TIME`,`LAST_MODIFY_TIME`,`OPERATOR`)
  VALUE ("首页",0,0,"/home",NULL ,NOW(),NOW(),1);


/*********************ADMIN_ROLE*************************/
DROP TABLE IF EXISTS `ADMIN_ROLE`;
CREATE TABLE `ADMIN_ROLE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `LAST_MODIFY_TIME` DATETIME DEFAULT NULL,
  `OPERATOR` BIGINT(20) DEFAULT NULL,
  `NAME` VARCHAR(20) COLLATE UTF8_BIN DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

INSERT ADMIN_ROLE(`NAME`,`CREATE_TIME`,`LAST_MODIFY_TIME`,`OPERATOR`)
  VALUE ("系统管理员",NOW(),NOW(),1);

/*********************ADMIN_USER*************************/
DROP TABLE IF EXISTS `ADMIN_USER`;
CREATE TABLE `ADMIN_USER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `LAST_MODIFY_TIME` DATETIME DEFAULT NULL,
  `OPERATOR` BIGINT(20) DEFAULT NULL,
  `PASSWORD` VARCHAR(64) COLLATE UTF8_BIN DEFAULT NULL,
  `NAME` VARCHAR(20) COLLATE UTF8_BIN DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_NAME` (`NAME`)
) ENGINE=INNODB AUTO_INCREMENT=9 DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

INSERT ADMIN_USER(`NAME`,`PASSWORD`,`CREATE_TIME`,`LAST_MODIFY_TIME`,`OPERATOR`)
  VALUE ("admin","a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",NOW(),NOW(),1);

/*********************ADMIN_USER_ROLE*************************/
DROP TABLE IF EXISTS `ADMIN_USER_ROLE`;
CREATE TABLE `ADMIN_USER_ROLE` (
  `USER_ID` BIGINT(20) NOT NULL,
  `ROLE_ID` BIGINT(20) NOT NULL,
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `LAST_MODIFY_TIME` DATETIME DEFAULT NULL,
  `OPERATOR` BIGINT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`USER_ID`,`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;
INSERT ADMIN_USER_ROLE(`USER_ID`,`ROLE_ID`,`CREATE_TIME`,`LAST_MODIFY_TIME`,`OPERATOR`)
  VALUE (1,1,NOW(),NOW(),1);

/*********************ADMIN_ROLE_PERMISSION*************************/
DROP TABLE IF EXISTS `ADMIN_ROLE_PERMISSION`;
CREATE TABLE `ADMIN_ROLE_PERMISSION` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_TIME` DATETIME DEFAULT NULL,
  `LAST_MODIFY_TIME` DATETIME DEFAULT NULL,
  `OPERATOR` BIGINT(20) DEFAULT NULL,
  `PERMISSION_ID` BIGINT(20) DEFAULT NULL,
  `ROLE_ID` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY (`ROLE_ID`,`PERMISSION_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_BIN;

INSERT ADMIN_ROLE_PERMISSION(`ROLE_ID`,`PERMISSION_ID`,`CREATE_TIME`,`LAST_MODIFY_TIME`,`OPERATOR`)
  VALUE (1,1,NOW(),NOW(),1);
